name: OpenWeb Podcast
description: Der Podcast über offene Standards im Internet
meta_description: "Der Podcast über offene Standards im Internet"

markdown: kramdown
highlighter: rouge
logo: false
cover: /img/owp-logo.jpg
paginate: 15
baseurl: /
domain_name: 'https://openwebpodcast.de'
gems: [jekyll-paginate]
plugins:
  - jekyll-sitemap
navigation:
    - label: Home
      url: /
    - label: About
      url: /about/
    - label: Fork on GitHub
      url: https://github.com/OpenWeb-Podcast/openweb-podcast.github.io/
    - label: Twitter
      url: https://twitter.com/openwebpodcast
    - label: Spotify
      url: https://open.spotify.com/show/4SlzdTof9Qih7aXwsJhIpl
    - label: Datenschutzerklärung
      url: /datenschutz/
    - label: Impressum
      url: /impressum/
